"""Test code_tag_collector."""

import re
from pathlib import Path

import pytest

from corallium.code_tag_collector._collector import (
    CODE_TAG_RE,
    COMMON_CODE_TAGS,
    SKIP_PHRASE,
    _CodeTag,
    _search_lines,
    github_blame_url,
    write_code_tag_file,
)


def test_skip_phrase_constant() -> None:
    """Verify SKIP_PHRASE uses corallium."""
    assert SKIP_PHRASE == 'corallium_skip_tags'


def test_common_code_tags() -> None:
    """Verify COMMON_CODE_TAGS contains expected tags."""
    assert 'TODO' in COMMON_CODE_TAGS
    assert 'FIXME' in COMMON_CODE_TAGS
    assert 'HACK' in COMMON_CODE_TAGS


def test_search_lines_finds_todo() -> None:
    """Test _search_lines finds TODO comments."""
    lines = [
        '# Some code',
        '# TODO: Fix this later',
        'def foo(): pass',
    ]
    regex = re.compile(CODE_TAG_RE.format(tag='TODO'))

    result = _search_lines(lines, regex)

    assert len(result) == 1
    assert result[0].tag == 'TODO'
    assert 'Fix this later' in result[0].text
    assert result[0].lineno == 2  # noqa: PLR2004


def test_search_lines_finds_multiple_tags() -> None:
    """Test _search_lines finds multiple different tags."""
    lines = [
        '# TODO: First task',
        '# FIXME: Broken code',
        '# HACK: Temporary workaround',
    ]
    regex = re.compile(CODE_TAG_RE.format(tag='|'.join(COMMON_CODE_TAGS)))

    result = _search_lines(lines, regex)

    assert len(result) == len(lines)
    assert result[0].tag == 'TODO'
    assert result[1].tag == 'FIXME'
    assert result[2].tag == 'HACK'


def test_search_lines_skips_file_with_skip_phrase() -> None:
    """Test _search_lines skips files with skip phrase."""
    lines = [
        '# TODO: This should be ignored',
        '',
        f'<!-- {SKIP_PHRASE} -->',
    ]
    regex = re.compile(CODE_TAG_RE.format(tag='TODO'))

    result = _search_lines(lines, regex)

    assert len(result) == 0


def test_search_lines_skips_long_lines() -> None:
    """Test _search_lines skips lines longer than 400 chars."""
    long_line = '# TODO: ' + 'x' * 500
    lines = [long_line]
    regex = re.compile(CODE_TAG_RE.format(tag='TODO'))

    result = _search_lines(lines, regex)

    assert len(result) == 0


def test_search_lines_with_custom_skip_phrase() -> None:
    """Test _search_lines respects custom skip phrase."""
    lines = [
        '# TODO: Should be found',
        '',
        '# custom_skip',
    ]
    regex = re.compile(CODE_TAG_RE.format(tag='TODO'))

    result = _search_lines(lines, regex, skip_phrase='custom_skip')

    assert len(result) == 0


@pytest.mark.parametrize(
    ('clone_uri', 'expected_url'),
    [
        ('git@github.com:KyleKing/corallium.git', 'https://github.com/KyleKing/corallium'),
        ('https://github.com/KyleKing/corallium.git', 'https://github.com/KyleKing/corallium'),
        ('https://github.com/KyleKing/corallium', 'https://github.com/KyleKing/corallium'),
        ('git@github.com:owner/repo.git', 'https://github.com/owner/repo'),
    ],
)
def test_github_blame_url_formats_correctly(clone_uri: str, expected_url: str) -> None:
    """Test github_blame_url formats various git URIs correctly."""
    result = github_blame_url(clone_uri)
    assert result == expected_url


def test_github_blame_url_returns_empty_for_invalid() -> None:
    """Test github_blame_url returns empty string for invalid URIs."""
    assert not github_blame_url('invalid-uri')
    assert not github_blame_url('https://gitlab.com/owner/repo.git')


def test_write_code_tag_file_creates_summary(tmp_path: Path) -> None:
    """Test write_code_tag_file creates a code tag summary file."""
    # Create test files with tags
    test_file = tmp_path / 'test.py'
    test_file.write_text('# TODO: Test task\n', encoding='utf-8')

    output_file = tmp_path / 'CODE_TAG_SUMMARY.md'

    write_code_tag_file(
        path_tag_summary=output_file,
        paths_source=[test_file],
        base_dir=tmp_path,
        tags='TODO',
    )

    assert output_file.is_file()
    content = output_file.read_text(encoding='utf-8')
    assert 'TODO' in content
    assert 'Test task' in content
    assert SKIP_PHRASE in content


def test_write_code_tag_file_with_custom_header(tmp_path: Path) -> None:
    """Test write_code_tag_file with custom header."""
    test_file = tmp_path / 'test.py'
    test_file.write_text('# FIXME: Bug here\n', encoding='utf-8')

    output_file = tmp_path / 'tags.md'
    custom_header = '# Custom Header\n\nGenerated by test'

    write_code_tag_file(
        path_tag_summary=output_file,
        paths_source=[test_file],
        base_dir=tmp_path,
        tags='FIXME',
        header=custom_header,
    )

    content = output_file.read_text(encoding='utf-8')
    assert 'Custom Header' in content
    assert 'FIXME' in content


def test_write_code_tag_file_no_tags_deletes_existing(tmp_path: Path) -> None:
    """Test write_code_tag_file deletes file when no tags found."""
    test_file = tmp_path / 'test.py'
    test_file.write_text('# No tags here\n', encoding='utf-8')

    output_file = tmp_path / 'tags.md'
    output_file.write_text('Old content\n', encoding='utf-8')

    write_code_tag_file(
        path_tag_summary=output_file,
        paths_source=[test_file],
        base_dir=tmp_path,
        tags='TODO',
    )

    assert not output_file.is_file()


def test_code_tag_dataclass() -> None:
    """Test _CodeTag dataclass is frozen."""
    tag = _CodeTag(lineno=10, tag='TODO', text='Test')

    with pytest.raises(AttributeError):
        tag.lineno = 20  # type: ignore[misc]
